apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::888045237793:user/uplus3-user
      username: uplus3-user
      groups:
        - system:masters